In [4]:
import pandas as pd

train_df = pd.read_parquet("top15_train.parquet")
test_df = pd.read_parquet("top15_test.parquet")

combined_df = pd.concat([train_df, test_df], ignore_index=True)
combined_df["data_split"] = ["train"] * len(train_df) + ["test"] * len(test_df)

combined_df.to_parquet("combined_dataset.parquet", index=False)

print("Combined shape:", combined_df.shape)
print("Columns:", list(combined_df.columns))
print(combined_df["data_split"].value_counts().to_string())

Combined shape: (210690, 20)
Columns: ['city_id', 'store_id', 'management_group_id', 'first_category_id', 'second_category_id', 'third_category_id', 'product_id', 'dt', 'sale_amount', 'hours_sale', 'stock_hour6_22_cnt', 'hours_stock_status', 'discount', 'holiday_flag', 'activity_flag', 'precpt', 'avg_temperature', 'avg_humidity', 'avg_wind_level', 'data_split']
data_split
train    175575
test      35115

In [5]:
combined_df.head()

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level,data_split
0,0,0,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.6999,15.48,73.54,1.97,train
1,0,1,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.3, 0.0, 0.0, ...",16,"[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7005,15.47,73.53,1.97,train
2,0,2,2,29,78,82,4,2024-03-28,1.3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...",0.882,0,1,1.7000,15.72,73.51,1.51,train
3,0,12,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.2, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7000,15.48,73.54,1.97,train
4,0,18,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0.814,0,1,1.7008,16.03,73.48,1.36,train

In [6]:
combined_df.isnull().sum()

city_id                0
store_id               0
management_group_id    0
first_category_id      0
second_category_id     0
third_category_id      0
product_id             0
dt                     0
sale_amount            0
hours_sale             0
stock_hour6_22_cnt     0
hours_stock_status     0
discount               0
holiday_flag           0
activity_flag          0
precpt                 0
avg_temperature        0
avg_humidity           0
avg_wind_level         0
data_split             0
dtype: int64

In [7]:
# import pandas as pd

# combined_df = combined_df.copy()
# combined_df["dt"] = pd.to_datetime(combined_df["dt"])
# combined_df = combined_df.sort_values(["product_id", "dt"]).reset_index(drop=True)

# split_frames = []
# for _, group in combined_df.groupby("product_id", sort=False):
#     group = group.sort_values("dt")
#     unique_dates = sorted(group["dt"].dropna().unique())

#     if len(unique_dates) < 15:
#         group["data_split"] = "train"
#     else:
#         cutoff_date = unique_dates[-15]
#         group["data_split"] = group["dt"].ge(cutoff_date).map({True: "test", False: "train"})

#     split_frames.append(group)

# combined_df = pd.concat(split_frames, ignore_index=True)
# train_df = combined_df[combined_df["data_split"] == "train"].copy()
# test_df = combined_df[combined_df["data_split"] == "test"].copy()

# print("Train rows:", len(train_df))
# print("Test rows:", len(test_df))
# print(train_df["data_split"].value_counts().to_string())
# print(test_df["data_split"].value_counts().to_string())

In [8]:
# train_df.head()

In [9]:
# import pandas as pd

# # Directly read the rows from test_df for product 4 on the requested day
# if 'test_df' in locals():
#     test_df_copy = test_df.copy()
#     test_df_copy['dt'] = pd.to_datetime(test_df_copy['dt'])
#     day_label = '2024_06_11'
#     sku_4_test = test_df_copy[
#         (test_df_copy['product_id'] == 4) &
#         (test_df_copy['dt'].dt.strftime('%Y_%m_%d') == day_label)&
#         (test_df_copy['store_id'] == 0)
#     ]
#     print(sku_4_test)
# else:
#     print('test_df is not available in this notebook context.')

In [10]:
# import numpy as np
# import pandas as pd
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Input, SimpleRNN, Dense
# from tensorflow.keras.optimizers import Adam

# # Use the combined dataset if it is already loaded; otherwise read it from disk
# if 'combined_df' not in locals():
#     combined_df = pd.read_parquet('combined_dataset.parquet')

# # Build a store-SKU hourly series for the example
# combined_df = combined_df.copy()
# combined_df['dt'] = pd.to_datetime(combined_df['dt'])

# # Keep only the columns needed for the example
# example_df = combined_df[['store_id', 'product_id', 'dt', 'hours_stock_status']].copy()

# # Expand the 24-hour stock status list into hourly rows
# example_df['hourly_status'] = example_df['hours_stock_status'].apply(lambda x: list(x) if isinstance(x, (list, np.ndarray)) else [])
# example_df = example_df.explode('hourly_status').reset_index(drop=True)
# example_df['hour'] = example_df.groupby(['store_id', 'product_id', 'dt']).cumcount()
# example_df['stock_status'] = example_df['hourly_status'].astype(int)
# # Encode a stockout as 1 and a non-stockout as 0 for binary classification
# example_df['stockout_label'] = (example_df['stock_status'] == 0).astype(int)

# # Keep one sequence per store-SKU pair
# store_sku_df = example_df[['store_id', 'product_id', 'dt', 'hour', 'stock_status', 'stockout_label']].copy()
# store_sku_df['timestamp'] = pd.to_datetime(store_sku_df['dt']) + pd.to_timedelta(store_sku_df['hour'], unit='h')
# store_sku_df = store_sku_df.sort_values(['store_id', 'product_id', 'timestamp']).reset_index(drop=True)

# # Pick one store-SKU pair for the example
# store_id = 0
# sku_id = 4
# pair_df = store_sku_df[(store_sku_df['store_id'] == store_id) & (store_sku_df['product_id'] == sku_id)].copy()
# pair_df = pair_df.sort_values('timestamp').reset_index(drop=True)
# series = pair_df['stockout_label'].to_numpy(dtype='float32')

# # Use the first 75 days for training and the next 15 days for testing
# train_days = 75
# train_len = train_days * 24
# forecast_horizon = 15 * 24
# lookback = 24


# def make_sequences(values, lookback):
#     X, y = [], []
#     for i in range(lookback, len(values)):
#         X.append(values[i-lookback:i])
#         y.append(values[i])
#     return np.array(X, dtype='float32').reshape(-1, lookback, 1), np.array(y, dtype='float32').reshape(-1, 1)

# X_train, y_train = make_sequences(series[:train_len], lookback)

# model = Sequential([
#     Input(shape=(lookback, 1)),
#     SimpleRNN(16, activation='tanh'),
#     Dense(1, activation='sigmoid')
# ])
# model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
# model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

# # Recursive one-step-ahead forecast for the next 15 days of hourly data
# history = series[:train_len][-lookback:].copy()
# forecast_prob = []
# for _ in range(forecast_horizon):
#     x = history[-lookback:].reshape(1, lookback, 1)
#     prob = model.predict(x, verbose=0)[0, 0]
#     forecast_prob.append(float(prob))
#     history = np.append(history, prob)

# actual = series[train_len:train_len + forecast_horizon]
# forecast_label = (np.array(forecast_prob) >= 0.5).astype(int)
# accuracy = np.mean(forecast_label == actual)

# print('Store:', store_id)
# print('SKU:', sku_id)
# print('Training hours:', train_len)
# print('Forecast horizon hours:', forecast_horizon)
# print('Forecast probabilities (first 10 hours):', np.round(forecast_prob[:10], 4))
# print('Predicted labels (first 10 hours):', forecast_label[:10])
# print('Original stock status (first 10 hours):', pair_df['stock_status'].iloc[train_len:train_len+10].astype(int).tolist())
# print('Encoded stockout labels (first 10 hours):', actual[:10].astype(int).tolist())
# print('Accuracy:', round(float(accuracy), 4))

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import StandardScaler

from tensorflow.keras import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    SimpleRNN,
    Lambda,
    Concatenate,
    Dense,
    Dropout,
)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.metrics import AUC
from tensorflow.keras.optimizers import Adam, RMSprop

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)

In [3]:
if 'combined_df' not in locals():
    combined_df = pd.read_parquet("combined_dataset.parquet")

combined_df = combined_df.copy()

combined_df["dt"] = pd.to_datetime(combined_df["dt"])

In [4]:
combined_df.head()

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level,data_split
0,0,0,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.6999,15.48,73.54,1.97,train
1,0,1,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.3, 0.0, 0.0, ...",16,"[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7005,15.47,73.53,1.97,train
2,0,2,2,29,78,82,4,2024-03-28,1.3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...",0.882,0,1,1.7000,15.72,73.51,1.51,train
3,0,12,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.2, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7000,15.48,73.54,1.97,train
4,0,18,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0.814,0,1,1.7008,16.03,73.48,1.36,train

In [ ]:
SERIES_COLUMNS = ["city_id", "store_id", "product_id"]
FEATURE_COLUMNS = [
    "sale_amount",
    "stock_hour6_22_cnt",
    "discount",
    "holiday_flag",
    "activity_flag",
    "precpt",
    "avg_temperature",
    "avg_humidity",
    "avg_wind_level",
    "hours_sale_sum",
    "hours_sale_max",
    "hours_stock_status_sum",
    "hours_stock_status_mean",
]
TARGET_COLUMNS = [f"target_stock_h{hour:02d}" for hour in range(24)]


def to_24_float_list(value, length=24):
    if isinstance(value, np.ndarray):
        values = value.tolist()
    elif isinstance(value, (list, tuple)):
        values = list(value)
    else:
        values = []

    values = [0.0 if pd.isna(item) else float(item) for item in values[:length]]
    if len(values) < length:
        values.extend([0.0] * (length - len(values)))
    return values


def add_series_id(data):
    data = data.copy()
    data["series_id"] = (
        data["city_id"].astype(str)
        + "_"
        + data["store_id"].astype(str)
        + "_"
        + data["product_id"].astype(str)
    )
    return data


def clean_frame_like_reference(data):
    data = add_series_id(data)
    data["dt"] = pd.to_datetime(data["dt"], errors="coerce")
    data = data.dropna(subset=["dt", *SERIES_COLUMNS])
    data = data.drop_duplicates(subset=["series_id", "dt"], keep="last")

    stock_matrix = np.array(
        data["hours_stock_status"].apply(to_24_float_list).tolist(),
        dtype=np.float32,
    )
    sales_matrix = np.array(
        data["hours_sale"].apply(to_24_float_list).tolist(),
        dtype=np.float32,
    )

    for hour in range(24):
        data[f"stock_h{hour:02d}"] = stock_matrix[:, hour]

    data["hours_sale_sum"] = sales_matrix.sum(axis=1)
    data["hours_sale_max"] = sales_matrix.max(axis=1)
    data["hours_stock_status_sum"] = stock_matrix.sum(axis=1)
    data["hours_stock_status_mean"] = data["hours_stock_status_sum"] / 24.0

    for column in FEATURE_COLUMNS:
        data[column] = pd.to_numeric(data[column], errors="coerce").fillna(0.0)

    return data.sort_values(["series_id", "dt"]).reset_index(drop=True)


def add_next_day_targets_like_reference(data):
    data = data.copy()
    stock_columns = [f"stock_h{hour:02d}" for hour in range(24)]
    for source_col, target_col in zip(stock_columns, TARGET_COLUMNS):
        data[target_col] = data.groupby("series_id")[source_col].shift(-1)
    return data.dropna(subset=TARGET_COLUMNS).reset_index(drop=True)

combined_df = clean_frame_like_reference(combined_df)
combined_df = add_next_day_targets_like_reference(combined_df)
combined_df[["series_id", "dt", "hours_stock_status_sum", *TARGET_COLUMNS[:4]]].head()

In [6]:
combined_df["avg_hourly_sales"] = combined_df["hours_sale"].apply(np.mean)

combined_df["max_hourly_sales"] = combined_df["hours_sale"].apply(np.max)

combined_df["std_hourly_sales"] = combined_df["hours_sale"].apply(np.std)

In [ ]:
feature_cols = FEATURE_COLUMNS
target_cols = TARGET_COLUMNS
TARGET_HOURS = 24

DEMAND_FEATURES = [
    "sale_amount",
    "discount",
    "holiday_flag",
    "hours_sale_sum",
]
INVENTORY_FEATURES = [
    "stock_hour6_22_cnt",
    "hours_stock_status_sum",
]

demand_indices = [feature_cols.index(feature) for feature in DEMAND_FEATURES]
inventory_indices = [feature_cols.index(feature) for feature in INVENTORY_FEATURES]

In [ ]:
scaler = StandardScaler()
train_mask = combined_df["data_split"].eq("train")

scaler.fit(combined_df.loc[train_mask, feature_cols])
combined_df[feature_cols] = scaler.transform(combined_df[feature_cols])

In [9]:
LOOKBACK = 14
TRAIN_DAYS = 75
TARGET_HOURS = 24

In [ ]:
X_train = []
y_train = []

X_test = []
y_test = []
sequence_meta_train = []
sequence_meta_test = []

for series_id, group in combined_df.groupby("series_id", sort=False):
    group = group.sort_values("dt").reset_index(drop=True)

    if len(group) <= LOOKBACK:
        continue

    features = group[feature_cols].to_numpy(dtype=np.float32)
    targets = group[target_cols].to_numpy(dtype=np.float32)
    dates = group["dt"].to_numpy()

    # Match the reference file: features[end-LOOKBACK:end] predict target day dates[end].
    # Because target columns are shifted, targets[end-1] is the next day's 24-hour vector.
    for end in range(LOOKBACK, len(group)):
        sample_x = features[end - LOOKBACK:end]
        sample_y = targets[end - 1]
        target_split = group.loc[end, "data_split"]
        meta = {"series_id": series_id, "target_date": str(pd.Timestamp(dates[end]).date())}

        if target_split == "train":
            X_train.append(sample_x)
            y_train.append(sample_y)
            sequence_meta_train.append(meta)
        elif target_split == "test":
            X_test.append(sample_x)
            y_test.append(sample_y)
            sequence_meta_test.append(meta)

In [11]:
X_train = np.array(X_train, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)

X_test = np.array(X_test, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)

In [12]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(145142, 14, 21)
(145142, 24)
(32774, 14, 21)
(32774, 24)

In [13]:
print("Training Variation 1: 24-Hour SimpleRNN Baseline")
model = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])),
    SimpleRNN(32, activation="tanh"),
    Dense(TARGET_HOURS, activation="sigmoid"),
])
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["binary_accuracy", AUC(name="auc"), AUC(name="pr_auc", curve="PR")],
)
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=64,
    verbose=1,
)

Training Variation 1: 24-Hour SimpleRNN Baseline

E0000 00:00:1786810432.982576   34693 cuda_executor.cc:1737] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1786810432.986937   55334 cuda_executor.cc:1755] Failed to determine cuDNN version (Note that this is expected if the application doesn't link the cuDNN plugin): INTERNAL: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
W0000 00:00:1786810433.161835   34693 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

Epoch 1/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 36s 13ms/step - auc: 0.8407 - binary_accuracy: 0.8044 - loss: 0.4221 - pr_auc: 0.6853 - val_auc: 0.8271 - val_binary_accuracy: 0.8152 - val_loss: 0.4155 - val_pr_auc: 0.6483
Epoch 2/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 23s 10ms/step - auc: 0.8628 - binary_accuracy: 0.8196 - loss: 0.3957 - pr_auc: 0.7252 - val_auc: 0.8293 - val_binary_accuracy: 0.8162 - val_loss: 0.4134 - val_pr_auc: 0.6504
Epoch 3/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 27s 12ms/step - auc: 0.8666 - binary_accuracy: 0.8220 - loss: 0.3906 - pr_auc: 0.7326 - val_auc: 0.8310 - val_binary_accuracy: 0.8154 - val_loss: 0.4125 - val_pr_auc: 0.6524
Epoch 4/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 23s 10ms/step - auc: 0.8693 - binary_accuracy: 0.8236 - loss: 0.3871 - pr_auc: 0.7375 - val_auc: 0.8281 - val_binary_accuracy: 0.8130 - val_loss: 0.4151 - val_pr_auc: 0.6474
Epoch 5/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 24s 10ms/step - auc: 0.8714 - binary_accuracy: 0.8249 - loss: 0.3843 - pr_auc: 0.7415 - val_auc: 0.8297 - val_binary_accuracy: 0.8131 - val_loss: 0.4129 - val_pr_auc: 0.6489
Epoch 6/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 34s 15ms/step - auc: 0.8730 - binary_accuracy: 0.8263 - loss: 0.3820 - pr_auc: 0.7450 - val_auc: 0.8290 - val_binary_accuracy: 0.8160 - val_loss: 0.4126 - val_pr_auc: 0.6519
Epoch 7/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 36s 16ms/step - auc: 0.8745 - binary_accuracy: 0.8275 - loss: 0.3799 - pr_auc: 0.7479 - val_auc: 0.8313 - val_binary_accuracy: 0.8132 - val_loss: 0.4124 - val_pr_auc: 0.6523
Epoch 8/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 31s 14ms/step - auc: 0.8757 - binary_accuracy: 0.8286 - loss: 0.3783 - pr_auc: 0.7500 - val_auc: 0.8311 - val_binary_accuracy: 0.8161 - val_loss: 0.4104 - val_pr_auc: 0.6547
Epoch 9/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 29s 13ms/step - auc: 0.8769 - binary_accuracy: 0.8294 - loss: 0.3767 - pr_auc: 0.7520 - val_auc: 0.8334 - val_binary_accuracy: 0.8167 - val_loss: 0.4089 - val_pr_auc: 0.6578
Epoch 10/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 27s 12ms/step - auc: 0.8779 - binary_accuracy: 0.8301 - loss: 0.3754 - pr_auc: 0.7536 - val_auc: 0.8321 - val_binary_accuracy: 0.8142 - val_loss: 0.4119 - val_pr_auc: 0.6551
Epoch 11/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 27s 12ms/step - auc: 0.8789 - binary_accuracy: 0.8307 - loss: 0.3741 - pr_auc: 0.7553 - val_auc: 0.8321 - val_binary_accuracy: 0.8129 - val_loss: 0.4118 - val_pr_auc: 0.6552
Epoch 12/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 28s 12ms/step - auc: 0.8796 - binary_accuracy: 0.8316 - loss: 0.3731 - pr_auc: 0.7566 - val_auc: 0.8299 - val_binary_accuracy: 0.8105 - val_loss: 0.4158 - val_pr_auc: 0.6518
Epoch 13/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 29s 13ms/step - auc: 0.8803 - binary_accuracy: 0.8317 - loss: 0.3722 - pr_auc: 0.7576 - val_auc: 0.8320 - val_binary_accuracy: 0.8090 - val_loss: 0.4141 - val_pr_auc: 0.6554
Epoch 14/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 30s 13ms/step - auc: 0.8809 - binary_accuracy: 0.8323 - loss: 0.3713 - pr_auc: 0.7591 - val_auc: 0.8302 - val_binary_accuracy: 0.8105 - val_loss: 0.4172 - val_pr_auc: 0.6501
Epoch 15/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 31s 14ms/step - auc: 0.8814 - binary_accuracy: 0.8327 - loss: 0.3707 - pr_auc: 0.7597 - val_auc: 0.8311 - val_binary_accuracy: 0.8063 - val_loss: 0.4165 - val_pr_auc: 0.6540
Epoch 16/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 29s 13ms/step - auc: 0.8820 - binary_accuracy: 0.8330 - loss: 0.3699 - pr_auc: 0.7607 - val_auc: 0.8315 - val_binary_accuracy: 0.8104 - val_loss: 0.4144 - val_pr_auc: 0.6528
Epoch 17/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 28s 13ms/step - auc: 0.8823 - binary_accuracy: 0.8332 - loss: 0.3695 - pr_auc: 0.7611 - val_auc: 0.8282 - val_binary_accuracy: 0.8081 - val_loss: 0.4172 - val_pr_auc: 0.6516
Epoch 18/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 28s 12ms/step - auc: 0.8827 - binary_accuracy: 0.8337 - loss: 0.3690 - pr_auc: 0.7617 - val_auc: 0.8256 - val_binary_accuracy: 0.8064 - val_loss: 0.4210 - val_pr_auc: 0.6480
Epoch 19/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 26s 12ms/step - auc: 0.8831 - binary_accuracy: 0.8337 - loss: 0.3684 - pr_auc: 0.7624 - val_auc: 0.8261 - val_binary_accuracy: 0.8087 - val_loss: 0.4183 - val_pr_auc: 0.6497
Epoch 20/20
2268/2268 ━━━━━━━━━━━━━━━━━━━━ 30s 13ms/step - auc: 0.8832 - binary_accuracy: 0.8340 - loss: 0.3682 - pr_auc: 0.7627 - val_auc: 0.8240 - val_binary_accuracy: 0.8085 - val_loss: 0.4200 - val_pr_auc: 0.6464

In [ ]:
def print_24h_metrics(model, X_eval, y_eval, threshold=0.5, name="Model"):
    loss, binary_accuracy, auc, pr_auc = model.evaluate(X_eval, y_eval, verbose=1)
    probabilities = model.predict(X_eval, batch_size=256, verbose=1)
    predictions = (probabilities >= threshold).astype(int)

    labels_flat = y_eval.astype(int).ravel()
    predictions_flat = predictions.ravel()

    print(f"{name} Test Loss:", loss)
    print(f"{name} Hour-Level Binary Accuracy @ {threshold}:", binary_accuracy)
    print(f"{name} Hour-Level Precision @ {threshold}:", precision_score(labels_flat, predictions_flat, zero_division=0))
    print(f"{name} Hour-Level Recall @ {threshold}:", recall_score(labels_flat, predictions_flat, zero_division=0))
    print(f"{name} Hour-Level F1 @ {threshold}:", f1_score(labels_flat, predictions_flat, zero_division=0))
    print(f"{name} ROC AUC:", auc)
    print(f"{name} PR AUC:", pr_auc)
    print(f"{name} Exact 24H Match Rate:", np.mean(np.all(predictions == y_eval.astype(int), axis=1)))
    print(f"{name} Mean Absolute Hour Count Error:", np.mean(
        np.abs(predictions.sum(axis=1) - y_eval.astype(int).sum(axis=1))
    ))

print_24h_metrics(model, X_test, y_test, threshold=0.5, name="SimpleRNN Baseline")

In [15]:
print("Training Variation 2: 24-Hour Higher Capacity SimpleRNN")
model_2 = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])),
    SimpleRNN(64, activation="tanh"),
    Dense(TARGET_HOURS, activation="sigmoid"),
])

model_2.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["binary_accuracy", AUC(name="auc"), AUC(name="pr_auc", curve="PR")],
)

history_2 = model_2.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1,
)

Training Variation 2: 24-Hour Higher Capacity SimpleRNN
Epoch 1/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 64s 13ms/step - auc: 0.8547 - binary_accuracy: 0.8140 - loss: 0.4061 - pr_auc: 0.7087 - val_auc: 0.8303 - val_binary_accuracy: 0.8149 - val_loss: 0.4130 - val_pr_auc: 0.6506
Epoch 2/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 70s 15ms/step - auc: 0.8714 - binary_accuracy: 0.8256 - loss: 0.3848 - pr_auc: 0.7398 - val_auc: 0.8258 - val_binary_accuracy: 0.8159 - val_loss: 0.4160 - val_pr_auc: 0.6470
Epoch 3/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 63s 14ms/step - auc: 0.8771 - binary_accuracy: 0.8297 - loss: 0.3771 - pr_auc: 0.7505 - val_auc: 0.8249 - val_binary_accuracy: 0.8126 - val_loss: 0.4187 - val_pr_auc: 0.6452
Epoch 4/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 54s 12ms/step - auc: 0.8811 - binary_accuracy: 0.8326 - loss: 0.3716 - pr_auc: 0.7577 - val_auc: 0.8253 - val_binary_accuracy: 0.8117 - val_loss: 0.4180 - val_pr_auc: 0.6445
Epoch 5/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 59s 13ms/step - auc: 0.8841 - binary_accuracy: 0.8349 - loss: 0.3674 - pr_auc: 0.7632 - val_auc: 0.8246 - val_binary_accuracy: 0.8104 - val_loss: 0.4228 - val_pr_auc: 0.6435
Epoch 6/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 52s 11ms/step - auc: 0.8864 - binary_accuracy: 0.8363 - loss: 0.3641 - pr_auc: 0.7673 - val_auc: 0.8268 - val_binary_accuracy: 0.8086 - val_loss: 0.4191 - val_pr_auc: 0.6410
Epoch 7/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 59s 13ms/step - auc: 0.8882 - binary_accuracy: 0.8376 - loss: 0.3616 - pr_auc: 0.7703 - val_auc: 0.8203 - val_binary_accuracy: 0.8004 - val_loss: 0.4271 - val_pr_auc: 0.6346
Epoch 8/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 59s 13ms/step - auc: 0.8893 - binary_accuracy: 0.8384 - loss: 0.3600 - pr_auc: 0.7721 - val_auc: 0.8206 - val_binary_accuracy: 0.7999 - val_loss: 0.4324 - val_pr_auc: 0.6367
Epoch 9/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 57s 13ms/step - auc: 0.8904 - binary_accuracy: 0.8393 - loss: 0.3584 - pr_auc: 0.7741 - val_auc: 0.8184 - val_binary_accuracy: 0.8006 - val_loss: 0.4320 - val_pr_auc: 0.6319
Epoch 10/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 58s 13ms/step - auc: 0.8915 - binary_accuracy: 0.8403 - loss: 0.3568 - pr_auc: 0.7761 - val_auc: 0.8188 - val_binary_accuracy: 0.7976 - val_loss: 0.4355 - val_pr_auc: 0.6322
Epoch 11/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 56s 12ms/step - auc: 0.8921 - binary_accuracy: 0.8405 - loss: 0.3559 - pr_auc: 0.7771 - val_auc: 0.8178 - val_binary_accuracy: 0.8062 - val_loss: 0.4305 - val_pr_auc: 0.6357
Epoch 12/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 60s 13ms/step - auc: 0.8929 - binary_accuracy: 0.8409 - loss: 0.3547 - pr_auc: 0.7786 - val_auc: 0.8227 - val_binary_accuracy: 0.7991 - val_loss: 0.4306 - val_pr_auc: 0.6404
Epoch 13/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 57s 12ms/step - auc: 0.8935 - binary_accuracy: 0.8417 - loss: 0.3539 - pr_auc: 0.7798 - val_auc: 0.8201 - val_binary_accuracy: 0.7956 - val_loss: 0.4344 - val_pr_auc: 0.6353
Epoch 14/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 54s 12ms/step - auc: 0.8941 - binary_accuracy: 0.8423 - loss: 0.3530 - pr_auc: 0.7809 - val_auc: 0.8196 - val_binary_accuracy: 0.8011 - val_loss: 0.4299 - val_pr_auc: 0.6325
Epoch 15/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 55s 12ms/step - auc: 0.8944 - binary_accuracy: 0.8425 - loss: 0.3524 - pr_auc: 0.7820 - val_auc: 0.8155 - val_binary_accuracy: 0.8028 - val_loss: 0.4353 - val_pr_auc: 0.6312
Epoch 16/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 59s 13ms/step - auc: 0.8947 - binary_accuracy: 0.8426 - loss: 0.3521 - pr_auc: 0.7819 - val_auc: 0.8193 - val_binary_accuracy: 0.7974 - val_loss: 0.4334 - val_pr_auc: 0.6342
Epoch 17/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 62s 14ms/step - auc: 0.8952 - binary_accuracy: 0.8428 - loss: 0.3513 - pr_auc: 0.7830 - val_auc: 0.8166 - val_binary_accuracy: 0.7917 - val_loss: 0.4405 - val_pr_auc: 0.6309
Epoch 18/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 64s 14ms/step - auc: 0.8957 - binary_accuracy: 0.8435 - loss: 0.3504 - pr_auc: 0.7843 - val_auc: 0.8202 - val_binary_accuracy: 0.8027 - val_loss: 0.4300 - val_pr_auc: 0.6366
Epoch 19/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 62s 14ms/step - auc: 0.8963 - binary_accuracy: 0.8440 - loss: 0.3496 - pr_auc: 0.7853 - val_auc: 0.8194 - val_binary_accuracy: 0.8004 - val_loss: 0.4334 - val_pr_auc: 0.6302
Epoch 20/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 68s 15ms/step - auc: 0.8965 - binary_accuracy: 0.8442 - loss: 0.3492 - pr_auc: 0.7860 - val_auc: 0.8228 - val_binary_accuracy: 0.8029 - val_loss: 0.4279 - val_pr_auc: 0.6367

In [16]:
print("Training Variation 3: 24-Hour Stacked SimpleRNN")
model_3 = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])),
    SimpleRNN(32, activation="tanh", return_sequences=True),
    SimpleRNN(16, activation="tanh"),
    Dense(TARGET_HOURS, activation="sigmoid"),
])

model_3.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["binary_accuracy", AUC(name="auc"), AUC(name="pr_auc", curve="PR")],
)

history_3 = model_3.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1,
)

Training Variation 3: 24-Hour Stacked SimpleRNN
Epoch 1/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 112s 23ms/step - auc: 0.8482 - binary_accuracy: 0.8099 - loss: 0.4139 - pr_auc: 0.6971 - val_auc: 0.8268 - val_binary_accuracy: 0.8117 - val_loss: 0.4162 - val_pr_auc: 0.6431
Epoch 2/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 95s 21ms/step - auc: 0.8675 - binary_accuracy: 0.8226 - loss: 0.3900 - pr_auc: 0.7324 - val_auc: 0.8250 - val_binary_accuracy: 0.8050 - val_loss: 0.4201 - val_pr_auc: 0.6390
Epoch 3/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 98s 22ms/step - auc: 0.8720 - binary_accuracy: 0.8259 - loss: 0.3838 - pr_auc: 0.7419 - val_auc: 0.8305 - val_binary_accuracy: 0.8104 - val_loss: 0.4144 - val_pr_auc: 0.6501
Epoch 4/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 103s 23ms/step - auc: 0.8752 - binary_accuracy: 0.8284 - loss: 0.3794 - pr_auc: 0.7479 - val_auc: 0.8273 - val_binary_accuracy: 0.8104 - val_loss: 0.4164 - val_pr_auc: 0.6432
Epoch 5/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 99s 22ms/step - auc: 0.8776 - binary_accuracy: 0.8304 - loss: 0.3762 - pr_auc: 0.7522 - val_auc: 0.8280 - val_binary_accuracy: 0.8106 - val_loss: 0.4173 - val_pr_auc: 0.6457
Epoch 6/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 93s 21ms/step - auc: 0.8795 - binary_accuracy: 0.8321 - loss: 0.3736 - pr_auc: 0.7559 - val_auc: 0.8217 - val_binary_accuracy: 0.8089 - val_loss: 0.4248 - val_pr_auc: 0.6391
Epoch 7/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 99s 22ms/step - auc: 0.8809 - binary_accuracy: 0.8329 - loss: 0.3716 - pr_auc: 0.7585 - val_auc: 0.8254 - val_binary_accuracy: 0.8110 - val_loss: 0.4220 - val_pr_auc: 0.6422
Epoch 8/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 99s 22ms/step - auc: 0.8822 - binary_accuracy: 0.8338 - loss: 0.3698 - pr_auc: 0.7608 - val_auc: 0.8242 - val_binary_accuracy: 0.8070 - val_loss: 0.4240 - val_pr_auc: 0.6375
Epoch 9/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 97s 21ms/step - auc: 0.8831 - binary_accuracy: 0.8345 - loss: 0.3685 - pr_auc: 0.7627 - val_auc: 0.8185 - val_binary_accuracy: 0.8027 - val_loss: 0.4311 - val_pr_auc: 0.6264
Epoch 10/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 99s 22ms/step - auc: 0.8840 - binary_accuracy: 0.8353 - loss: 0.3672 - pr_auc: 0.7644 - val_auc: 0.8180 - val_binary_accuracy: 0.8064 - val_loss: 0.4333 - val_pr_auc: 0.6315
Epoch 11/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 102s 22ms/step - auc: 0.8848 - binary_accuracy: 0.8360 - loss: 0.3661 - pr_auc: 0.7658 - val_auc: 0.8208 - val_binary_accuracy: 0.8085 - val_loss: 0.4280 - val_pr_auc: 0.6381
Epoch 12/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 100s 22ms/step - auc: 0.8856 - binary_accuracy: 0.8363 - loss: 0.3650 - pr_auc: 0.7673 - val_auc: 0.8161 - val_binary_accuracy: 0.8082 - val_loss: 0.4334 - val_pr_auc: 0.6340
Epoch 13/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 107s 24ms/step - auc: 0.8861 - binary_accuracy: 0.8368 - loss: 0.3641 - pr_auc: 0.7683 - val_auc: 0.8217 - val_binary_accuracy: 0.8023 - val_loss: 0.4309 - val_pr_auc: 0.6295
Epoch 14/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 101s 22ms/step - auc: 0.8868 - binary_accuracy: 0.8372 - loss: 0.3632 - pr_auc: 0.7694 - val_auc: 0.8245 - val_binary_accuracy: 0.8111 - val_loss: 0.4254 - val_pr_auc: 0.6454
Epoch 15/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 99s 22ms/step - auc: 0.8873 - binary_accuracy: 0.8376 - loss: 0.3625 - pr_auc: 0.7702 - val_auc: 0.8183 - val_binary_accuracy: 0.8025 - val_loss: 0.4351 - val_pr_auc: 0.6280
Epoch 16/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 107s 24ms/step - auc: 0.8879 - binary_accuracy: 0.8379 - loss: 0.3617 - pr_auc: 0.7711 - val_auc: 0.8200 - val_binary_accuracy: 0.8044 - val_loss: 0.4341 - val_pr_auc: 0.6316
Epoch 17/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 98s 22ms/step - auc: 0.8883 - binary_accuracy: 0.8381 - loss: 0.3611 - pr_auc: 0.7718 - val_auc: 0.8218 - val_binary_accuracy: 0.8088 - val_loss: 0.4295 - val_pr_auc: 0.6371
Epoch 18/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 71s 16ms/step - auc: 0.8889 - binary_accuracy: 0.8388 - loss: 0.3602 - pr_auc: 0.7731 - val_auc: 0.8180 - val_binary_accuracy: 0.7985 - val_loss: 0.4356 - val_pr_auc: 0.6264
Epoch 19/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 58s 13ms/step - auc: 0.8891 - binary_accuracy: 0.8389 - loss: 0.3600 - pr_auc: 0.7733 - val_auc: 0.8158 - val_binary_accuracy: 0.7983 - val_loss: 0.4385 - val_pr_auc: 0.6202
Epoch 20/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 65s 14ms/step - auc: 0.8895 - binary_accuracy: 0.8389 - loss: 0.3594 - pr_auc: 0.7738 - val_auc: 0.8211 - val_binary_accuracy: 0.8046 - val_loss: 0.4326 - val_pr_auc: 0.6322

In [ ]:
print("Training Variation 4: 24-Hour Dropout, Dense, and RMSprop")
model_4 = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])),
    SimpleRNN(32, activation="tanh", dropout=0.2, recurrent_dropout=0.2),
    Dense(16, activation="relu"),
    Dense(TARGET_HOURS, activation="sigmoid"),
])

model_4.compile(
    optimizer=RMSprop(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["binary_accuracy", AUC(name="auc"), AUC(name="pr_auc", curve="PR")],
)

history_4 = model_4.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1,
)

Training Variation 4: 24-Hour Dropout, Dense, and RMSprop
Epoch 1/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 50s 10ms/step - auc: 0.8339 - binary_accuracy: 0.8004 - loss: 0.4295 - pr_auc: 0.6715 - val_auc: 0.8287 - val_binary_accuracy: 0.8153 - val_loss: 0.4136 - val_pr_auc: 0.6485
Epoch 2/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 41s 9ms/step - auc: 0.8524 - binary_accuracy: 0.8132 - loss: 0.4083 - pr_auc: 0.7058 - val_auc: 0.8310 - val_binary_accuracy: 0.8170 - val_loss: 0.4109 - val_pr_auc: 0.6534
Epoch 3/20
4536/4536 ━━━━━━━━━━━━━━━━━━━━ 44s 10ms/step - auc: 0.8547 - binary_accuracy: 0.8146 - loss: 0.4052 - pr_auc: 0.7113 - val_auc: 0.8321 - val_binary_accuracy: 0.8130 - val_loss: 0.4134 - val_pr_auc: 0.6487
Epoch 4/20
4533/4536 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - auc: 0.8563 - binary_accuracy: 0.8156 - loss: 0.4033 - pr_auc: 0.7143

In [ ]:
print("Training Variation 5: 24-Hour ReLU SimpleRNN with Gradient Clipping")
model_5 = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])),
    SimpleRNN(32, activation="relu"),
    Dense(TARGET_HOURS, activation="sigmoid"),
])

optimizer_5 = Adam(learning_rate=0.001, clipnorm=1.0)

model_5.compile(
    optimizer=optimizer_5,
    loss="binary_crossentropy",
    metrics=["binary_accuracy", AUC(name="auc"), AUC(name="pr_auc", curve="PR")],
)

history_5 = model_5.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1,
)

In [ ]:
print_24h_metrics(model_2, X_test, y_test, threshold=0.5, name="SimpleRNN 64")

In [ ]:
print_24h_metrics(model_3, X_test, y_test, threshold=0.5, name="Stacked SimpleRNN")

In [ ]:
print_24h_metrics(model_4, X_test, y_test, threshold=0.5, name="Dropout SimpleRNN")

In [ ]:
print_24h_metrics(model_5, X_test, y_test, threshold=0.5, name="ReLU SimpleRNN")

In [ ]:
print("Train hourly label distribution")
print(pd.Series(y_train.ravel()).value_counts())
print("\nTest hourly label distribution")
print(pd.Series(y_test.ravel()).value_counts())

In [ ]:
def evaluate_24h_predictions(model, X_eval, y_eval, threshold=0.5, batch_size=256):
    probabilities = model.predict(X_eval, batch_size=batch_size, verbose=1)
    predictions = (probabilities >= threshold).astype(int)
    labels_flat = y_eval.astype(int).ravel()
    predictions_flat = predictions.ravel()

    return {
        "threshold": threshold,
        "hour_level_accuracy": accuracy_score(labels_flat, predictions_flat),
        "hour_level_precision": precision_score(labels_flat, predictions_flat, zero_division=0),
        "hour_level_recall": recall_score(labels_flat, predictions_flat, zero_division=0),
        "hour_level_f1": f1_score(labels_flat, predictions_flat, zero_division=0),
        "exact_24h_match_rate": np.mean(np.all(predictions == y_eval.astype(int), axis=1)),
        "mean_absolute_hour_count_error": np.mean(
            np.abs(predictions.sum(axis=1) - y_eval.astype(int).sum(axis=1))
        ),
    }

evaluate_24h_predictions(model, X_test, y_test, threshold=0.5)

In [ ]:
def build_dual_stream_rnn_24h_model(
    lookback,
    n_features,
    demand_indices,
    inventory_indices,
    target_hours=24,
):
    inputs = Input(shape=(lookback, n_features))

    demand_stream = Lambda(lambda x: tf.gather(x, demand_indices, axis=-1))(inputs)
    inventory_stream = Lambda(lambda x: tf.gather(x, inventory_indices, axis=-1))(inputs)

    demand_branch = SimpleRNN(16, activation="tanh", dropout=0.10)(demand_stream)
    inventory_branch = SimpleRNN(16, activation="tanh", dropout=0.10)(inventory_stream)
    full_branch = SimpleRNN(32, activation="tanh", dropout=0.10)(inputs)

    combined = Concatenate()([demand_branch, inventory_branch, full_branch])
    dense = Dense(32, activation="relu")(combined)
    dense = Dropout(0.20)(dense)
    outputs = Dense(target_hours, activation="sigmoid")(dense)

    model = Model(inputs, outputs, name="dual_stream_simplernn_24h")
    model.compile(
        optimizer=Adam(learning_rate=0.001, clipnorm=1.0),
        loss="binary_crossentropy",
        metrics=["binary_accuracy", AUC(name="auc"), AUC(name="pr_auc", curve="PR")],
    )
    return model

model_6 = build_dual_stream_rnn_24h_model(
    LOOKBACK,
    X_train.shape[2],
    demand_indices,
    inventory_indices,
    TARGET_HOURS,
)
model_6.summary()

In [ ]:
positive_hours = float(y_train.sum())
total_hours = float(y_train.size)
negative_hours = total_hours - positive_hours
positive_weight = negative_hours / max(positive_hours, 1.0)

# Keras class_weight is awkward for multi-label 24-output targets, so this mirrors
# BCEWithLogitsLoss(pos_weight=...) from the reference file using weighted BCE.
def weighted_binary_crossentropy(pos_weight):
    def loss(y_true, y_pred):
        epsilon = 1e-7
        y_pred = tf.clip_by_value(y_pred, epsilon, 1.0 - epsilon)
        return tf.reduce_mean(
            -(pos_weight * y_true * tf.math.log(y_pred) + (1.0 - y_true) * tf.math.log(1.0 - y_pred))
        )
    return loss

model_6.compile(
    optimizer=Adam(learning_rate=0.001, clipnorm=1.0),
    loss=weighted_binary_crossentropy(positive_weight),
    metrics=["binary_accuracy", AUC(name="auc"), AUC(name="pr_auc", curve="PR")],
)

callbacks_6 = [
    EarlyStopping(
        monitor="val_pr_auc",
        mode="max",
        patience=4,
        restore_best_weights=True,
        verbose=1,
    ),
    ReduceLROnPlateau(
        monitor="val_pr_auc",
        mode="max",
        factor=0.5,
        patience=2,
        min_lr=1e-5,
        verbose=1,
    ),
]

print("Positive hour weight:", positive_weight)
print("Training Variation 6: Reference-Style Dual-Stream SimpleRNN 24H")
history_6 = model_6.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=30,
    batch_size=64,
    callbacks=callbacks_6,
    verbose=1,
)

In [ ]:
print_24h_metrics(model_6, X_test, y_test, threshold=0.5, name="Dual-Stream SimpleRNN 24H")

In [ ]:
y_prob_6 = model_6.predict(X_test, batch_size=256, verbose=1)

threshold_results = []
for threshold in np.arange(0.30, 0.71, 0.01):
    y_pred_threshold = (y_prob_6 >= threshold).astype(int)
    labels_flat = y_test.astype(int).ravel()
    predictions_flat = y_pred_threshold.ravel()
    threshold_results.append({
        "threshold": round(float(threshold), 2),
        "hour_level_accuracy": accuracy_score(labels_flat, predictions_flat),
        "hour_level_precision": precision_score(labels_flat, predictions_flat, zero_division=0),
        "hour_level_recall": recall_score(labels_flat, predictions_flat, zero_division=0),
        "hour_level_f1": f1_score(labels_flat, predictions_flat, zero_division=0),
        "exact_24h_match_rate": np.mean(np.all(y_pred_threshold == y_test.astype(int), axis=1)),
        "mean_absolute_hour_count_error": np.mean(
            np.abs(y_pred_threshold.sum(axis=1) - y_test.astype(int).sum(axis=1))
        ),
    })

threshold_df = pd.DataFrame(threshold_results)
best_accuracy_row = threshold_df.loc[threshold_df["hour_level_accuracy"].idxmax()]
best_f1_row = threshold_df.loc[threshold_df["hour_level_f1"].idxmax()]
best_recall_row = threshold_df.loc[threshold_df["hour_level_recall"].idxmax()]

print("Best threshold by hour-level accuracy")
print(best_accuracy_row)
print("\nBest threshold by hour-level F1")
print(best_f1_row)
print("\nBest threshold by hour-level recall")
print(best_recall_row)
threshold_df.sort_values("hour_level_accuracy", ascending=False).head(10)

In [ ]:
store = 0
sku = 4
prediction_day = pd.Timestamp("2024-06-11")

group = combined_df[
    (combined_df["store_id"] == store) &
    (combined_df["product_id"] == sku)
].sort_values("dt")

history = group[group["dt"] < prediction_day].tail(LOOKBACK)

if len(history) != LOOKBACK:
    print("Only found history rows:", len(history))
else:
    X_one = history[feature_cols].values.astype(np.float32).reshape(1, LOOKBACK, len(feature_cols))
    hourly_prob = model_6.predict(X_one, verbose=0)[0]
    hourly_pred = (hourly_prob >= float(best_accuracy_row["threshold"])).astype(int)

    print("Predicted stock status for each of next 24 hours:")
    print(hourly_pred.tolist())
    print("Hourly probabilities:")
    print(np.round(hourly_prob, 3).tolist())